// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi9rrsxCNWd30ic1XcCFQ5GxuSC4KUjno',
    appId: '1:868320905482:web:5087e872e18107f40652f3',
    messagingSenderId: '868320905482',
    projectId: 'sales-management-app-c7ff3',
    authDomain: 'sales-management-app-c7ff3.firebaseapp.com',
    storageBucket: 'sales-management-app-c7ff3.firebasestorage.app',
    measurementId: 'G-SE3FHDHFK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtVifUqBW6qCZTKzplQv9i9oSYKgikSHY',
    appId: '1:868320905482:android:a55f72305c9ece6f0652f3',
    messagingSenderId: '868320905482',
    projectId: 'sales-management-app-c7ff3',
    storageBucket: 'sales-management-app-c7ff3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSzXZ_PWAB7PgWILoghWiYTKo3mQCxTSg',
    appId: '1:868320905482:ios:5411f376ac0c4b440652f3',
    messagingSenderId: '868320905482',
    projectId: 'sales-management-app-c7ff3',
    storageBucket: 'sales-management-app-c7ff3.firebasestorage.app',
    iosBundleId: 'com.example.salesManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSzXZ_PWAB7PgWILoghWiYTKo3mQCxTSg',
    appId: '1:868320905482:ios:5411f376ac0c4b440652f3',
    messagingSenderId: '868320905482',
    projectId: 'sales-management-app-c7ff3',
    storageBucket: 'sales-management-app-c7ff3.firebasestorage.app',
    iosBundleId: 'com.example.salesManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi9rrsxCNWd30ic1XcCFQ5GxuSC4KUjno',
    appId: '1:868320905482:web:4fa6392d796eca640652f3',
    messagingSenderId: '868320905482',
    projectId: 'sales-management-app-c7ff3',
    authDomain: 'sales-management-app-c7ff3.firebaseapp.com',
    storageBucket: 'sales-management-app-c7ff3.firebasestorage.app',
    measurementId: 'G-HY5X8KENGY',
  );
}
